jobs:
  include:
    - language: python
      python: 3.6
      install:
        - cd config
        - pip install -r requirements.txt
        - pip install -r test-requirements.txt
      script:
        - pytest test.py
    - language: node
      node_js:
        - "8"
      install:
        - npm install
        - npm run-script build
      script:
        - npm test