language: python
sudo: required
services:
  - docker

# Below lines from https://github.com/travis-ci/travis-ci/issues/5358#issuecomment-248915326

cache:
  bundler: true
  directories:
    - $HOME/docker

script:
  - sudo ./test.sh
