language: python
python: 3.6
node_js: 8
install:
  - cd router
  - npm install
  - npm run-script build
  - cd ../config-server
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
script:
  - pytest test.py
  - cd ../router
  - npm test