version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    networks: [app]
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.3
    depends_on:
      - "elasticsearch"
    ports:
      - "5601:5601"
    networks: [app]
  configserver:
    build: config-server
    ports:
      - "8081:8080"
    depends_on:
      - "elasticsearch"
    networks: [app]
    env_file: [config.env]
  router:
    build: router
    ports:
      - "8082:8080"
    depends_on:
      - "elasticsearch"
      - "configserver"
    networks: [app]
  frontend:
    build:
      context: front-end
      args:
        - CONFIG_SERVER
        - ROUTING_SERVER
    ports:
      - "8080:80"
    depends_on:
      - "configserver"
    networks: [app]
    env_file: [config.env]
networks:
  app:
    ipam:
      driver: default
      config:
        - subnet: 11.10.11.1/22