version: '3'
services:
  frontend:
    build:
      dockerfile: ./dev.Dockerfile
    volumes:
      - ./front-end:/front-end
      - "./config.json:/front-end/config.json"
  configserver:
    volumes:
      - "./config.json:/config-server/config.json"
      - ./config-server:/config-server
    environment:
      POSTGRES_PASSWORD: a_password
  firewallconfig:
    volumes:
      - ./firewall-config:/firewall-config
  router:
    volumes:
      - ./router:/router
    environment:
      CONFIGSERVER_LOCATION: http://configserver:8080
      ELASTICSEARCH_HOST: elasticsearch
  db:
    environment:
      POSTGRES_PASSWORD: a_password

