version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    networks: [app]
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.3
    depends_on:
      - "elasticsearch"
    ports:
      - "5601:5601"
    networks: [app]
  configserver:
    build: config-server
    ports:
      - "8081:8080"
    depends_on:
      - "elasticsearch"
    networks: [app]
    volumes:
      - "./config.json:/config-server/config.json"
  router:
    build: router
    ports:
      - "8082:8080"
    depends_on:
      - "elasticsearch"
      - "configserver"
    networks: [app]
  frontend:
    build: front-end
    ports:
      - "8080:80"
    depends_on:
      - "configserver"
    networks: [app]
    volumes:
      - "./config.json:/usr/local/apache2/htdocs/config.json"
networks:
  app:
    driver_opts:
      com.docker.network.driver.mtu: 1400
    ipam:
      driver: default
      config:
        - subnet: 10.11.0.1/22
