version: '3'
services:
  frontend:
    ports:
      - "8080:8080"
    build:
      dockerfile: ./dev.Dockerfile
    volumes:
      - ./front-end:/front-end
      - "./config.json:/front-end/config.json"
  configserver:
    volumes:
      - "./config.json:/config-server/config.json"
      - ./config-server:/config-server
  firewallconfig:
    volumes:
      - ./firewall-config:/firewall-config
  router:
    volumes:
      - ./router:/router
