swagger: "2.0"
info:
  version: 1.0.0
  title: Webhook router
  license:
    name: MIT
host: 127.0.0.1
paths:
  /route/{token}:
    parameters:
      - name: token
        in: path
        required: true
        description: The token of the route
        type: string
    post:
      summary: Location to send webhooks to, in order for them to be routed
      operationId: server.routeWebhook
      responses:
        '200':
          description: Webhook routed correctly
        default:
          description: unexpected error
          schema:
            $ref: "#/definitions/Error"
  /view-routes:
    get:
      summary: Gets all routes that are configured for given user
      operationId: server.getAllRoutes
      responses:
        '200':
          description: Returns the given routes
          schema:
            $ref: "#/definitions/Routes"
        default:
          description: unexpected error
          schema:
            $ref: "#/definitions/Error"
  /OAS:
    get:
      summary: Gets the OpenAPI Specification
      operationId: server.getOAS
      responses:
        '200':
          description: Returns the given routes
        default:
          description: unexpected error
          schema:
            $ref: "#/definitions/Error"
  /add-route:
    post:
      summary: Gets all routes that are configured
      operationId: server.addRoute
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/NewRoute"
      responses:
        '200':
          description: Expected response to a valid request
          schema:
            $ref: "#/definitions/Route"
        default:
          description: unexpected error
          schema:
            $ref: "#/definitions/Error"
definitions:
  NewRoute:
    required:
      - name
      - destination
      - write-users
    properties:
      name:
        type: string
      destination:
        type: string
      write-users:
        type: array
        items:
          type: string
  Route:
    allOf:
      - $ref: "#/definitions/NewRoute"
      - required:
          - token
        properties:
          token:
            type: string
  Routes:
    type: array
    items:
      $ref: "#/definitions/Route"
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
